Added support for Single and Completable responses
xmartlabs/Opera pull request #35
Opened 2017-04-24 20:25 UTC by m-revetria

Changes proposed:

* Support for new `Single` and `Completable` sequence types from `RxSwift`. Fixes #33 
* **Breaking change**: the return type of `var PaginationRequestType.collection` has been changed from `Observable<Base.Response>` to `Single<Base.Response>`* Old functions using `Observable` has been deprecated.
* Fixed compilation warnings

2017-04-25 13:03 UTC, mcousillas6 commented on Sources/Common/RxManager.swift
> +        return base.response(requestConvertible)
🎉

2017-04-25 13:04 UTC, mcousillas6 commented on Sources/Common/RxManager.swift
> +        return Completable.empty()
Does this work? If it is like Observable.empty() this will never emit to the subscriber

2017-04-25 13:08 UTC, mcousillas6 commented on Sources/Common/RxManager.swift
> +        return Completable.empty()
My bad, this will call onComplete.

2017-04-25 13:09 UTC, mcousillas6 approved these changes

2017-04-26 14:40 UTC, dernster requested changes

2017-04-26 14:40 UTC, dernster commented on Sources/Common/Error.swift
> +
Isn't `components.append("Networking Error: \((error as CustomStringConvertible).debugDescription)")` missing?

2017-04-26 14:40 UTC, dernster commented on Sources/Common/RouteType+Rx.swift
> +        return (base.manager as! RxManager).rx.sampleCompletableResponse(base)
`sampleCompletableResponse` and `completableResponse` are swapped?

2017-04-26 14:41 UTC, m-revetria commented on Sources/Common/RouteType+Rx.swift
> +        return (base.manager as! RxManager).rx.sampleCompletableResponse(base)
looks like, yes. I'll take care of it

2017-04-26 14:45 UTC, m-revetria commented on Sources/Common/Error.swift
> +
Yes I noticed it, but as this is the implementation of the `description` property I think it is ok. You can check that there are other minor differences with the implementation of `debugDescroption` like the JSON value which is not included in the error's `description`. What do you think?

2017-04-27 12:59 UTC, dernster approved these changes

2017-04-27 17:34 UTC, merged